// Generated by CoffeeScript 1.3.3
(function() {
  var RA;

  RA = window.RA = {};

  RA.holds = function(condition, vars) {
    var gtmatch;
    if (condition === 'always') {
      return true;
    }
    gtmatch = /$$\S+ > $$\S+/.exec(conditon);
    return console.log(gtmatch);
  };

  RA.fillout = function(content, vars) {
    return content;
  };

  RA.do_section = function(name, section) {
    var text, _i, _len, _ref, _results;
    alert("doing " + name);
    _ref = section.texts;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      text = _ref[_i];
      if (RA.holds(text.condition, text.vars)) {
        _results.push($('body').append(RA.fillout(text.content, text.vars)));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  RA.start = function() {
    var doc, name, section, _ref;
    doc = {
      sections: {
        intro: {
          vars: {
            a: 10,
            b: 12
          },
          texts: [
            {
              condition: 'always',
              content: 'A is $$a.'
            }, {
              condition: '$$a > $$b',
              content: 'That is larger than B, which is $$b.'
            }
          ]
        }
      }
    };
    console.log(doc);
    _ref = doc.sections;
    for (name in _ref) {
      section = _ref[name];
      RA.do_section(name, section);
    }
    return false;
  };

  $(function() {
    return RA.start();
  });

}).call(this);
