// Generated by CoffeeScript 1.3.3
(function() {

  window.RA || (window.RA = {});

  Parse.initialize("41lsI7DmaFx8DFDLgvmO4Ewu0sBGW6iziRrseXyP", "eittl0BlCWcgKRbQQLkPA04MLEy2wQfXc68rYA0z");

}).call(this);
