// Generated by CoffeeScript 1.3.3
(function() {

  window.RA || (window.RA = {});

  RA.Views || (RA.Views = {});

  RA.Views.DatasetFull = Backbone.View.extend({
    tagName: 'div',
    className: 'fulldataset',
    events: {
      'click .name': 'handleNameClick'
    },
    initialize: function() {
      _.bindAll(this, 'changeName');
      return this.model.bind('change:name', this.changeName);
    },
    changeName: function() {
      return alert('name changed');
    },
    handleNameClick: function() {
      return alert('tickled on name');
    },
    render: function() {
      var html, name, value, varname, _ref;
      html = '';
      name = this.model.get('name');
      html += "<h3 class='name'>" + name + "</h3>";
      html += '<dl>';
      _ref = this.model.get('vars');
      for (varname in _ref) {
        value = _ref[varname];
        html += "<dt class='var" + varname + "'>" + varname + "</dt><dd>" + value + "</dd>";
      }
      html += '</dl>';
      alert(html);
      this.$el.innerHTML(html);
      return this;
    }
  });

}).call(this);
