// Generated by CoffeeScript 1.3.3
(function() {

  window.RA || (window.RA = {});

  RA.Models || (RA.Models = {});

  RA.Models.App = Backbone.Model.extend({
    initialize: function() {
      this.datasets = new RA.Collections.Datasets();
      return this.documents = new RA.Collections.Documents();
    },
    fetch: function() {
      var ds;
      ds = this.datasets;
      this.datasets.fetch({
        success: function(collection) {
          return console.log("got datasets");
        },
        error: function() {
          return console.warn("didn't get datasets");
        }
      });
      return this.documents.fetch({
        success: function(collection) {
          console.log("got documents");
          return collection.trigger('change');
        },
        error: function() {
          return console.warn("didn't get documents");
        }
      });
    }
  });

}).call(this);
