// Generated by CoffeeScript 1.3.3
(function() {

  window.RA || (window.RA = {});

  RA.Collections || (RA.Collections = {});

  RA.Collections.Documents = Backbone.Collection.extend({
    model: RA.Models.Document
  });

}).call(this);
